export const REQUEST_PROJECT = 'REQUEST_PROJECT';
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';

export const REQUEST_DATASETS = 'REQUEST_DATASETS';
export const RECEIVE_DATASETS = 'RECEIVE_DATASETS';

export const REQUEST_UPLOAD_DATASET = 'REQUEST_UPLOAD_DATASET';
export const RECEIVE_UPLOAD_DATASET = 'RECEIVE_UPLOAD_DATASET';

