export const REQUEST_PROJECT = 'REQUEST_PROJECT';
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';

export const REQUEST_DATASET = 'REQUEST_DATASET';
export const RECEIVE_DATASET = 'RECEIVE_DATASET';

export const REQUEST_DATASETS = 'REQUEST_DATASETS';
export const RECEIVE_DATASETS = 'RECEIVE_DATASETS';

export const REQUEST_UPLOAD_DATASET = 'REQUEST_UPLOAD_DATASET';
export const RECEIVE_UPLOAD_DATASET = 'RECEIVE_UPLOAD_DATASET';

export const REQUEST_SPECS = 'REQUEST_SPECS';
export const RECEIVE_SPECS = 'RECEIVE_SPECS';

export const SELECT_DATASET = 'SELECT_DATASET';

export const SELECT_VISUALIZATION_TYPE = 'SELECT_VISUALIZATION_TYPE';
