export const REQUEST_CREATE_SAVED_AGGREGATION = 'REQUEST_CREATE_SAVED_AGGREGATION';
export const RECEIVE_CREATED_SAVED_AGGREGATION = 'RECEIVE_CREATED_SAVED_AGGREGATION';
export const REQUEST_CREATE_EXPORTED_AGGREGATION = 'REQUEST_CREATE_EXPORTED_AGGREGATION';
export const RECEIVE_CREATED_EXPORTED_AGGREGATION = 'RECEIVE_CREATED_EXPORTED_AGGREGATION';

export const SELECT_AGGREGATION_AGGREGATION_VARIABLE = 'SELECT_AGGREGATION_AGGREGATION_VARIABLE';
export const SELECT_AGGREGATION_INDEPENDENT_VARIABLE = 'SELECT_AGGREGATION_INDEPENDENT_VARIABLE';
export const SELECT_AGGREGATION_AGGREGATION_FUNCTION = 'SELECT_AGGREGATION_AGGREGATION_FUNCTION';
export const SELECT_AGGREGATION_AGGREGATION_WEIGHT_VARIABLE = 'SELECT_AGGREGATION_AGGREGATION_WEIGHT_VARIABLE';
export const SELECT_AGGREGATION_CONFIG_X = 'SELECT_AGGREGATION_CONFIG_X';
export const SELECT_AGGREGATION_CONFIG_Y = 'SELECT_AGGREGATION_CONFIG_Y';

export const REQUEST_AGGREGATION_STATISTICS = 'REQUEST_AGGREGATION_STATISTICS';
export const RECEIVE_AGGREGATION_STATISTICS = 'RECEIVE_AGGREGATION_STATISTICS';
export const PROGRESS_AGGREGATION_STATISTICS = 'PROGRESS_AGGREGATION_STATISTICS';
export const ERROR_AGGREGATION_STATISTICS = 'ERROR_AGGREGATION_STATISTICS';

export const REQUEST_ONE_D_AGGREGATION = 'REQUEST_ONE_D_AGGREGATION';
export const RECEIVE_ONE_D_AGGREGATION = 'RECEIVE_ONE_D_AGGREGATION';
export const PROGRESS_ONE_D_AGGREGATION = 'PROGRESS_ONE_D_AGGREGATION';
export const ERROR_ONE_D_AGGREGATION = 'ERROR_ONE_D_AGGREGATION';

export const REQUEST_AGGREGATION = 'REQUEST_AGGREGATION';
export const RECEIVE_AGGREGATION = 'RECEIVE_AGGREGATION';
export const PROGRESS_AGGREGATION = 'PROGRESS_AGGREGATION';
export const ERROR_AGGREGATION = 'ERROR_AGGREGATION';
