export const REQUEST_EXPORTED_VISUALIZATION_SPECS = 'REQUEST_EXPORTED_VISUALIZATION_SPECS';
export const RECEIVE_EXPORTED_VISUALIZATION_SPECS = 'RECEIVE_EXPORTED_VISUALIZATION_SPECS';

export const REQUEST_EXPORTED_CORRELATIONS = 'REQUEST_EXPORTED_CORRELATIONS';
export const RECEIVE_EXPORTED_CORRELATIONS = 'RECEIVE_EXPORTED_CORRELATIONS';

export const REQUEST_EXPORTED_REGRESSIONS = 'REQUEST_EXPORTED_REGRESSIONS';
export const RECEIVE_EXPORTED_REGRESSIONS = 'RECEIVE_EXPORTED_REGRESSIONS';

export const SELECT_DOCUMENT = 'SELECT_DOCUMENT';

export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS';
export const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';

export const REQUEST_CREATE_DOCUMENT = 'REQUEST_CREATE_DOCUMENT';
export const RECEIVE_CREATE_DOCUMENT = 'RECEIVE_CREATE_DOCUMENT';

export const REQUEST_UPDATE_DOCUMENT = 'REQUEST_UPDATE_DOCUMENT';
export const RECEIVE_UPDATE_DOCUMENT = 'RECEIVE_UPDATE_DOCUMENT';

export const REQUEST_DELETE_DOCUMENT = 'REQUEST_DELETE_DOCUMENT';
export const RECEIVE_DELETE_DOCUMENT = 'RECEIVE_DELETE_DOCUMENT';

export const SELECT_COMPOSE_CONTENT = 'SELECT_COMPOSE_CONTENT';
export const REMOVE_COMPOSE_CONTENT = 'REMOVE_COMPOSE_CONTENT';

export const MOVE_COMPOSE_BLOCK = 'MOVE_COMPOSE_BLOCK';

export const SAVE_BLOCK = 'SAVE_BLOCK';
export const SET_DOCUMENT_TITLE = 'SET_DOCUMENT_TITLE';

export const REQUEST_SAVE_DOCUMENT = 'REQUEST_SAVE_DOCUMENT';
export const RECEIVE_SAVE_DOCUMENT = 'RECEIVE_SAVE_DOCUMENT';

export const REQUEST_PUBLISHED_DOCUMENT = 'REQUEST_PUBLISHED_DOCUMENT';
export const RECEIVE_PUBLISHED_DOCUMENT = 'RECEIVE_PUBLISHED_DOCUMENT';

export const REQUEST_EXPORT_POWERPOINT = 'REQUEST_EXPORT_POWERPOINT';
export const RECEIVE_EXPORT_POWERPOINT = 'RECEIVE_EXPORT_POWERPOINT';
