export const COMPARISON_MODE = 'COMPARISON_MODE';

export const SELECT_COMPARISON_INDEPENDENT_VARIABLE = 'SELECT_COMPARISON_INDEPENDENT_VARIABLE';
export const SELECT_COMPARISON_DEPENDENT_VARIABLE = 'SELECT_COMPARISON_DEPENDENT_VARIABLE';

export const REQUEST_NUMERICAL_COMPARISON = 'SELECT_COMPARISON_DEPENDENT_VARIABLE';
export const RECEIVE_NUMERICAL_COMPARISON = 'RECEIVE_NUMERICAL_COMPARISON';

export const UPDATE_COMPARISON_INPUT = 'UPDATE_COMPARISON_INPUT';

export const REQUEST_ANOVA = 'REQUEST_ANOVA';
export const RECEIVE_ANOVA = 'RECEIVE_ANOVA';

export const REQUEST_ANOVA_BOXPLOT_DATA = 'REQUEST_ANOVA_BOXPLOT_DATA';
export const RECEIVE_ANOVA_BOXPLOT_DATA = 'RECEIVE_ANOVA_BOXPLOT_DATA';

export const REQUEST_PAIRWISE_COMPARISON_DATA = 'REQUEST_PAIRWISE_COMPARISON_DATA';
export const RECEIVE_PAIRWISE_COMPARISON_DATA = 'RECEIVE_PAIRWISE_COMPARISON_DATA';

export const SET_COMPARISON_QUERY_STRING = 'SET_COMPARISON_QUERY_STRING';
