export const COMPARISON_MODE = 'COMPARISON_MODE';

export const SELECT_COMPARISON_INDEPENDENT_VARIABLE = 'SELECT_COMPARISON_INDEPENDENT_VARIABLE';
export const SELECT_COMPARISON_DEPENDENT_VARIABLE = 'SELECT_COMPARISON_DEPENDENT_VARIABLE';

export const REQUEST_COMPARISON = 'REQUEST_COMPARISON';
export const PROGRESS_COMPARISON = 'PROGRESS_COMPARISON';
export const RECEIVE_COMPARISON = 'RECEIVE_COMPARISON';
export const ERROR_COMPARISON = 'ERROR_COMPARISON';

export const REQUEST_CREATE_SAVED_COMPARISON = 'REQUEST_CREATE_SAVED_COMPARISON';
export const RECEIVE_CREATED_SAVED_COMPARISON = 'RECEIVE_CREATED_SAVED_COMPARISON';
export const REQUEST_CREATE_EXPORTED_COMPARISON = 'REQUEST_CREATE_EXPORTED_COMPARISON';
export const RECEIVE_CREATED_EXPORTED_COMPARISON = 'RECEIVE_CREATED_EXPORTED_COMPARISON';

export const UPDATE_COMPARISON_INPUT = 'UPDATE_COMPARISON_INPUT';

export const SET_COMPARISON_QUERY_STRING = 'SET_COMPARISON_QUERY_STRING';
