export const CONTENT_TYPES = {
  TEXT: 'TEXT',
  VISUALIZATION: 'VISUALIZATION',
  REGRESSION: 'REGRESSION',
  CORRELATION: 'CORRELATION',
  AGGREGATION: 'AGGREGATION',
  COMPARISON: 'COMPARISON',  
}
