export const SELECT_CORRELATION_VARIABLE = 'SELECT_CORRELATION_VARIABLE';

export const REQUEST_CORRELATION = 'REQUEST_CORRELATION';
export const RECEIVE_CORRELATION = 'RECEIVE_CORRELATION';
export const PROGRESS_CORRELATION = 'PROGRESS_CORRELATION';
export const ERROR_CORRELATION = 'ERROR_CORRELATION';

export const REQUEST_CORRELATION_SCATTERPLOT = 'REQUEST_CORRELATION_SCATTERPLOT';
export const RECEIVE_CORRELATION_SCATTERPLOT = 'RECEIVE_CORRELATION_SCATTERPLOT';

export const REQUEST_CREATE_SAVED_CORRELATION = 'REQUEST_CREATE_SAVED_CORRELATION';
export const RECEIVE_CREATED_SAVED_CORRELATION = 'RECEIVE_CREATED_SAVED_CORRELATION';
export const REQUEST_CREATE_EXPORTED_CORRELATION = 'REQUEST_CREATE_EXPORTED_CORRELATION';
export const RECEIVE_CREATED_EXPORTED_CORRELATION = 'RECEIVE_CREATED_EXPORTED_CORRELATION';