export const REQUEST_DATASET = 'REQUEST_DATASET';
export const RECEIVE_DATASET = 'RECEIVE_DATASET';

export const REQUEST_DATASETS = 'REQUEST_DATASETS';
export const RECEIVE_DATASETS = 'RECEIVE_DATASETS';

export const DELETED_DATASET = 'DELETED_DATASET';

export const REQUEST_UPLOAD_DATASET = 'REQUEST_UPLOAD_DATASET';
export const PROGRESS_UPLOAD_DATASET = 'PROGRESS_UPLOAD_DATASET';
export const ERROR_UPLOAD_DATASET = 'ERROR_UPLOAD_DATASET';
export const RECEIVE_UPLOAD_DATASET = 'RECEIVE_UPLOAD_DATASET';

export const SELECT_DATASET = 'SELECT_DATASET';

export const SELECT_DATASET_LAYOUT_TYPE = 'SELECT_DATASET_LAYOUT_TYPE';

export const REQUEST_REDUCE_DATASET_COLUMNS = 'REQUEST_REDUCE_DATASET_COLUMNS';
export const REQUEST_MERGE_DATASETS = 'REQUEST_MERGE_DATASETS';

export const PROGRESS_TRANSFORM = 'PROGRESS_TRANSFORM';
