export const AUTH_ERROR = 'AUTH_ERROR';
export const GENERAL_ERROR = 'GENERAL_ERROR';
export const BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR';
export const NOT_FOUND_ERROR = 'NOT_FOUND_ERROR';
export const REQUEST_TIMEOUT_ERROR = 'REQUEST_TIMEOUT_ERROR';
