export const SELECT_FIELD_PROPERTY = 'SELECT_FIELD_PROPERTY';

export const REQUEST_FIELD_PROPERTIES = 'REQUEST_FIELD_PROPERTIES';
export const RECEIVE_FIELD_PROPERTIES = 'RECEIVE_FIELD_PROPERTIES';

export const SELECT_FIELD_PROPERTY_VALUE = 'SELECT_FIELD_PROPERTY_VALUE';

export const REQUEST_SET_FIELD_TYPE = 'REQUEST_SET_FIELD_TYPE';
export const RECEIVE_SET_FIELD_TYPE = 'RECEIVE_SET_FIELD_TYPE';

export const REQUEST_SET_FIELD_IS_ID = 'REQUEST_SET_FIELD_IS_ID';
export const RECEIVE_SET_FIELD_IS_ID = 'RECEIVE_SET_FIELD_IS_ID';

export const REQUEST_SET_FIELD_COLOR = 'REQUEST_SET_FIELD_COLOR';
export const RECEIVE_SET_FIELD_COLOR = 'RECEIVE_SET_FIELD_COLOR';

export const SELECT_AGGREGATION_FUNCTION = 'SELECT_AGGREGATION_FUNCTION';
