export const REQUEST_PRELOADED_DATASETS = 'REQUEST_PRELOADED_DATASETS';
export const RECEIVE_PRELOADED_DATASETS = 'RECEIVE_PRELOADED_DATASETS';
export const SELECT_PRELOADED_DATASET = 'SELECT_PRELOADED_DATASET';

export const REQUEST_SELECT_PRELOADED_DATASET = 'REQUEST_SELECT_PRELOADED_DATASET';
export const RECEIVE_SELECT_PRELOADED_DATASET = 'RECEIVE_SELECT_PRELOADED_DATASET';
