export const REQUEST_CREATE_SAVED_SEGMENTATION = 'REQUEST_CREATE_SAVED_SEGMENTATION';
export const RECEIVE_CREATED_SAVED_SEGMENTATION = 'RECEIVE_CREATED_SAVED_SEGMENTATION';
export const REQUEST_CREATE_EXPORTED_SEGMENTATION = 'REQUEST_CREATE_EXPORTED_SEGMENTATION';
export const RECEIVE_CREATED_EXPORTED_SEGMENTATION = 'RECEIVE_CREATED_EXPORTED_SEGMENTATION';

export const SELECT_SEGMENTATION_SEGMENTATION_VARIABLE = 'SELECT_SEGMENTATION_SEGMENTATION_VARIABLE';
export const SELECT_SEGMENTATION_INDEPENDENT_VARIABLE = 'SELECT_SEGMENTATION_INDEPENDENT_VARIABLE';
export const SELECT_SEGMENTATION_SEGMENTATION_FUNCTION = 'SELECT_SEGMENTATION_SEGMENTATION_FUNCTION';
export const SELECT_SEGMENTATION_SEGMENTATION_WEIGHT_VARIABLE = 'SELECT_SEGMENTATION_SEGMENTATION_WEIGHT_VARIABLE';
export const SELECT_SEGMENTATION_CONFIG_X = 'SELECT_SEGMENTATION_CONFIG_X';
export const SELECT_SEGMENTATION_CONFIG_Y = 'SELECT_SEGMENTATION_CONFIG_Y';

export const REQUEST_SEGMENTATION_STATISTICS = 'REQUEST_SEGMENTATION_STATISTICS';
export const RECEIVE_SEGMENTATION_STATISTICS = 'RECEIVE_SEGMENTATION_STATISTICS';
export const PROGRESS_SEGMENTATION_STATISTICS = 'PROGRESS_SEGMENTATION_STATISTICS';
export const ERROR_SEGMENTATION_STATISTICS = 'ERROR_SEGMENTATION_STATISTICS';

export const REQUEST_ONE_D_SEGMENTATION = 'REQUEST_ONE_D_SEGMENTATION';
export const RECEIVE_ONE_D_SEGMENTATION = 'RECEIVE_ONE_D_SEGMENTATION';
export const PROGRESS_ONE_D_SEGMENTATION = 'PROGRESS_ONE_D_SEGMENTATION';
export const ERROR_ONE_D_SEGMENTATION = 'ERROR_ONE_D_SEGMENTATION';

export const REQUEST_SEGMENTATION = 'REQUEST_SEGMENTATION';
export const RECEIVE_SEGMENTATION = 'RECEIVE_SEGMENTATION';
export const PROGRESS_SEGMENTATION = 'PROGRESS_SEGMENTATION';
export const ERROR_SEGMENTATION = 'ERROR_SEGMENTATION';
