export const CREATE_ANONYMOUS_USER = 'CREATE_ANONYMOUS_USER';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SUBMIT_USER = 'SUBMIT_USER';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const RECEIVE_LOGIN_USER = 'RECEIVE_LOGIN_USER';
export const ERROR_LOGIN_USER = 'ERROR_LOGIN_USER';

export const REQUEST_LOGOUT_USER = 'REQUEST_LOGOUT_USER';
export const RECEIVE_LOGOUT_USER = 'RECEIVE_LOGOUT_USER';
export const ERROR_LOGOUT_USER = 'ERROR_LOGOUT_USER';

export const REQUEST_REGISTER_USER = 'REQUEST_REGISTER_USER';
export const RECEIVE_REGISTER_USER = 'RECEIVE_REGISTER_USER';
export const ERROR_REGISTER_USER = 'ERROR_REGISTER_USER';