export const SELECT_VISUALIZATION_TYPE = 'SELECT_VISUALIZATION_TYPE';
export const SELECT_SINGLE_VISUALIZATION_VISUALIZATION_TYPE = 'SELECT_SINGLE_VISUALIZATION_VISUALIZATION_TYPE';
export const SELECT_SORTING_FUNCTION = 'SELECT_SORTING_FUNCTION';
export const SELECT_SINGLE_VISUALIZATION_SORT_ORDER = 'SELECT_SINGLE_VISUALIZATION_SORT_ORDER';
export const SELECT_SINGLE_VISUALIZATION_SORT_FIELD = 'SELECT_SINGLE_VISUALIZATION_SORT_FIELD';
export const SELECT_CONDITIONAL = 'SELECT_CONDITIONAL';
export const DELETE_CONDITIONAL = 'DELETE_CONDITIONAL';

export const SELECT_VISUALIZATION_BINNING_CONFIG = 'SELECT_VISUALIZATION_BINNING_CONFIG';

export const CLEAR_VISUALIZATION = 'CLEAR_VISUALIZATION';

export const REQUEST_VISUALIZATION_DATA = 'REQUEST_VISUALIZATION_DATA';
export const RECEIVE_VISUALIZATION_DATA = 'RECEIVE_VISUALIZATION_DATA';

export const REQUEST_CREATE_EXPORTED_SPEC = 'REQUEST_CREATE_EXPORTED_SPEC';
export const RECEIVE_CREATED_EXPORTED_SPEC = 'RECEIVE_CREATED_EXPORTED_SPEC';

export const REQUEST_EXPORTED_SPEC = 'REQUEST_EXPORTED_SPEC';
export const RECEIVE_EXPORTED_SPEC = 'RECEIVE_EXPORTED_SPEC';

export const REQUEST_CREATE_SAVED_SPEC = 'REQUEST_CREATE_SAVED_SPEC';
export const RECEIVE_CREATED_SAVED_SPEC = 'RECEIVE_CREATED_SAVED_SPEC';

export const REQUEST_EXACT_SPECS = 'REQUEST_EXACT_SPECS';
export const PROGRESS_EXACT_SPECS = 'PROGRESS_EXACT_SPECS';
export const RECEIVE_EXACT_SPECS = 'RECEIVE_EXACT_SPECS';
export const FAILED_RECEIVE_EXACT_SPECS = 'FAILED_RECEIVE_EXACT_SPECS';
export const REQUEST_INDIVIDUAL_SPECS = 'REQUEST_INDIVIDUAL_SPECS';
export const PROGRESS_INDIVIDUAL_SPECS = 'PROGRESS_INDIVIDUAL_SPECS';
export const RECEIVE_INDIVIDUAL_SPECS = 'RECEIVE_INDIVIDUAL_SPECS';
export const FAILED_RECEIVE_INDIVIDUAL_SPECS = 'FAILED_RECEIVE_INDIVIDUAL_SPECS';
export const REQUEST_SUBSET_SPECS = 'REQUEST_SUBSET_SPECS';
export const PROGRESS_SUBSET_SPECS = 'PROGRESS_SUBSET_SPECS';
export const RECEIVE_SUBSET_SPECS = 'RECEIVE_SUBSET_SPECS';
export const FAILED_RECEIVE_SUBSET_SPECS = 'FAILED_RECEIVE_SUBSET_SPECS';
export const REQUEST_EXPANDED_SPECS = 'REQUEST_EXPANDED_SPECS';
export const PROGRESS_EXPANDED_SPECS = 'PROGRESS_EXPANDED_SPECS';
export const RECEIVE_EXPANDED_SPECS = 'RECEIVE_EXPANDED_SPECS';
export const FAILED_RECEIVE_EXPANDED_SPECS = 'FAILED_RECEIVE_EXPANDED_SPECS';
export const PROGRESS_SPECS = 'PROGRESS_SPECS';
export const FAILED_RECEIVE_SPECS = 'FAILED_RECEIVE_SPECS';

export const SELECT_RECOMMENDATION_MODE = 'SELECT_RECOMMENDATION_MODE';

export const SET_EXPLORE_QUERY_STRING = 'SET_EXPLORE_QUERY_STRING';

export const SELECT_VISUALIZATION_CONFIG = 'SELECT_VISUALIZATION_CONFIG';
