angular.module('diveApp.project').controller("OverviewCtrl", function($scope, $http, $state, $stateParams, Config) {
  console.log("[CONTROLLER] Overview");
  return $scope.removeProject = function(pID) {
    console.log('Removing project, pID:', pID);
    return $http["delete"](Config.API + '/api/project', {
      params: {
        pID: pID
      }
    }).success(function(result) {
      return $state.go('landing');
    });
  };
});

// ---
// generated by coffee-script 1.9.0
