var $, angular, angularCookies, angularTouch, diveApp;

angular = require('angular');

angularTouch = require('angular-touch');

angularCookies = require('angular-cookies');

require('angular-aria');
require('angular-animate');
require('angular-material');
require('slider');

require('./routes');
require('./data_service');
require('../modules/landing/landing.module');
require('../modules/project/project.module');
require('../modules/data/data.module');
require('../modules/property/property.module');
require('../modules/visualization/visualization.module');
require('../modules/export/export.module');
require('../modules/embed/embed.module');

diveApp = angular.module('diveApp', ['LocalStorageModule', 'ngAnimate', 'ngAria', 'ngMaterial', 'vr.directives.slider', 'diveApp.routes', 'diveApp.project', 'diveApp.landing', 'diveApp.data', 'diveApp.property', 'diveApp.visualization', 'diveApp.export', 'diveApp.embed']).constant('API_URL', 'http://localhost:8888');

diveApp.config(function (localStorageServiceProvider) {
  localStorageServiceProvider.setPrefix('dive').setNotify(true, true);
})

window.SC = function(selector) {
  return angular.element(selector).scope();
};

window.objectToQueryString = function(obj) {
  var p, str;
  str = [];
  for (p in obj) {
    str.push(encodeURIComponent(p) + "=" + encodeURIComponent(obj[p]));
  }
  return str.join("&");
};

window.formatRouteParam = function(str) {
  return str.trim().replace(/"/g, "");
};

window.onresize = function(e) {
  var mainViewHeight;
  mainViewHeight = $(window).height() - $("header").height();
  return $("div.wrapper").height(mainViewHeight);
};

$ = require('jquery');

angular.module('diveApp').directive('ngEnter', function() {
  return function(scope, element, attrs) {
    return element.bind('keydown keypress', function(event) {
      if (event.which === 13) {
        scope.$apply(function() {
          return scope.$eval(attrs.ngEnter, {
            'event': event
          });
        });
        return event.preventDefault();
      }
    });
  };
});

diveApp.filter("capitalize", function() {
  return function(input, scope) {
    if (input) {
      input = input.toLowerCase();
      return input.substring(0, 1).toUpperCase() + input.substring(1);
    } else {
      return input;
    }
  };
});

String.prototype.endsWith = function(suffix) {
    return this.indexOf(suffix, this.length - suffix.length) !== -1;
};

// TODO Make this more robust
diveApp.filter("pluralize", function() {
  return function(input, scope) {
    if (input.endsWith('s')) {
      return input;
    } else {
      return input + 's';
    }
  };
});

angular.element(document).ready(function() {
  var mainViewHeight;
  mainViewHeight = $(window).height() - $("header").height();
  return $("div.wrapper").height(mainViewHeight);
});

// ---
// generated by coffee-script 1.9.0